version = 0.1
[default]
[default.global.parameters]
no_telemetry = true

[default.deploy]
[default.deploy.parameters]
stack_name = "screen-translate"
region = "ap-northeast-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
s3_bucket = "screen-trans-b"
parameter_overrides = "TargetLanguage=\"zh\" CertificateArn=\"arn:aws:acm:ap-northeast-1:872515255237:certificate/3ef9837d-cfbe-462f-bd19-4925bf095508\""
resolve_s3 = true
s3_prefix = "screen-translate"
image_repositories = ["screentranslateFunction=872515255237.dkr.ecr.ap-northeast-1.amazonaws.com/screentranslate9b818dea/screentranslatefunctiona42c94cerepo"]
