AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Screen translation lambda function with Docker image

Parameters:
  ApiPassword:
    Type: String
    NoEcho: true
  TargetLanguage:
    Type: String
    Default: 'zh'
  VolcAccessKey:
    Type: String
    NoEcho: true
  VolcSecretKey:
    Type: String
    NoEcho: true
  CertificateArn:
    Type: String
    Description: ARN of the SSL certificate in AWS Certificate Manager

Resources:
  screentranslateFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageConfig:
        Command: ["index.handler"]
      MemorySize: 512
      Timeout: 60
      Environment:
        Variables:
          API_PASSWORD: !Ref ApiPassword
          NODE_OPTIONS: '--experimental-vm-modules'
          TARGET_LANGUAGE: !Ref TargetLanguage
          VOLC_ACCESS_KEY: !Ref VolcAccessKey
          VOLC_SECRET_KEY: !Ref VolcSecretKey
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /
            Method: ANY
            Auth:
              ApiKeyRequired: true
            RestApiId: !Ref ApiGatewayApi
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerTag: latest

  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Domain:
        DomainName: trans.mmclouds.org
        CertificateArn: !Ref CertificateArn
        EndpointConfiguration: REGIONAL
        SecurityPolicy: TLS_1_2
