AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Application Model template describing your function.

Parameters:
  ApiPassword:
    Type: String
    NoEcho: true
  TargetLanguage:
    Type: String
    Default: 'zh'
  VolcAccessKey:
    Type: String
    NoEcho: true
  VolcSecretKey:
    Type: String
    NoEcho: true

Resources:
  screentranslatescreentranslateMyFunctionK4HhM3froVBGaQnuPsLu:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 30
      Handler: index.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      Environment:
        Variables:
          API_PASSWORD: !Ref ApiPassword
          NODE_OPTIONS: '--experimental-vm-modules'
          TARGET_LANGUAGE: !Ref TargetLanguage
          VOLC_ACCESS_KEY: !Ref VolcAccessKey
          VOLC_SECRET_KEY: !Ref VolcSecretKey
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      Layers:
        - arn:aws:lambda:ap-northeast-1:872515255237:layer:sharp:2
      PackageType: Zip
      Policies:
        - Statement:
            - Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: '*'
              Effect: Allow
      RecursiveLoop: Terminate
      SnapStart:
        ApplyOn: None
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /
            Method: ANY
            Auth:
              ApiKeyRequired: true
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
